### ISSUE TITLE
Add `.isValidSignature()` method

### ISSUE THREAD

**Issue by Hugoo** [ERC725Alliance/erc725.js#104]
### I'm submitting a...

- feature request

### Summary

```js
await myERC725.isValidSignature("Message or hash", signature);
```

If the input parameter is hex + 32 bytes long (char length == 66 AND starts with or without 0x) -> then we assume the input is a hash -> no pre hash before check.
If not, the lib should hash the input first.

Then, it calls `.isValidSignature()` on the contract used at init.
If we get the magic value `0x1626ba7e` -> returns true
If not -> returns false

If call error -> throw error which says "Does the address ${init contract address} support EIP-1271?"

Because the lib can be init with asset or non UP account SC addresses

### Other information

- <https://eips.ethereum.org/EIPS/eip-1271>
- Add documentation accordingly

**Comment by CallumGrindle** [comment]
This could also be a static method taking an address as a param. Then we can instantiate the contract using `isValidSignature` abi to check if valid

```javascript
Erc725.isValidSignature("Message or hash", address);
```

**Comment by frozeman** [comment]
its actually 

```js
await ERC725orInstance.isValidSignature("Message or hash", signature[, upAddress]);
```
but ideally we adopt a options object, that other functions could also use:
```js
await ERC725orInstance.isValidSignature("Message or hash", signature[, { //options object
     address: ....
}]);
```
This way we can add more things later, without extending the function number

**Comment by frozeman** [comment]
Then no options object necessary
