### ISSUE TITLE
Source map wrong

### ISSUE THREAD

**Issue by frozeman** [ERC725Alliance/erc725.js#141]
```
Could not load content for http://localhost:3000/node_modules/@erc725/erc725.js/src/index.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

when clicking on the code lines in chrome dev tools.
The file is actually in 
`http://localhost:3000/node_modules/@erc725/erc725.js/main/module/src/index.ts` (or so)

**Comment by Hugoo** [comment]
I checked it but I'd like to see with you how to reproduce your issue.

On a NextJS project (https://github.com/lukso-network/tools-erc725-inspect) with dev build it works:

![image](https://user-images.githubusercontent.com/477945/169087281-da9ba546-ba9e-4a5c-be43-9769199f0d53.png)

![image](https://user-images.githubusercontent.com/477945/169087400-a8a9bdff-c57a-43fd-ad29-a08cae7f7f7a.png)
