### ISSUE TITLE
Allow user to encode json. Currently he must hash json first and then encode the hashed json.

### ISSUE THREAD

**Issue by antoniopgs** [ERC725Alliance/erc725.js#16]

**Comment by robertdavid010** [comment]
This is currently beyond the scope of the featureset, and is a categorical extension of said featureset. I'm not sure this is appropriate to do in this library, as there are other libraries which would this.

**Comment by rryter** [comment]
I think this could actually be a helpful feature, let's discuss this @robertdavid010 and check if we can include it in some upcoming changes. Or would you @antoniopgs be willing to provide a PR?

There is also already a todo in the code for this:
https://github.com/ERC725Alliance/erc725.js/blob/main/src/lib/encoder.ts#L226

**Comment by frozeman** [comment]
I agree, we actually already hash it when using `.fetchData()` here: https://github.com/ERC725Alliance/erc725.js/blob/087e9bcb5a5445b2c017aaf0aec2f5828f6a1aa3/src/index.ts#L408
, so we can easily encode JSON files with the hash. 

@rryter can you add this to your TODO pls?

something like:
```js
erc725.encodeData('LSP3Profile', {
    json: myJson,
    url: 'https://myURL.com/jsonfile.json'
 })
// coud return
0x6f357c6a828dc0b16e548a1dc32a3730413cf06b52ab87ac877c72bc50c4500f2d71d23e697066733a2f2f516d664c3753616a6f35486345327570556538596b6b3177576a58535535654b5733454d35707a444a4b456e506e

```

**Comment by antoniopgs** [comment]
@frozeman why not reduce it to one argument only? either:
- pass in the json, and the ipfs cid is calculated in the background
- pass in the cid, and the json gets processed in the background

why make the user provide two inputs which can be derived from each other?

**Comment by rryter** [comment]
@antoniopgs People can upload their files wherever they want, it's not guaranteed to be on IPFS.
@frozeman It's added on my TODO.
