### ISSUE TITLE
Wrong return type for `fetchData`

### ISSUE THREAD

**Issue by CallumGrindle** [ERC725Alliance/erc725.js#192]
When fetching profile await erc725.fetchData("LSP3Profile") expected return type is DecodeDataOutput with value field. But value  is typed as string | string[] | URLDataWithHash while in value  I get profile object

```
LSP3Profile: {
...
}
```

![image](https://user-images.githubusercontent.com/54543428/174992296-8089cdb0-3f78-476b-9871-273679354bee.png)

![image](https://user-images.githubusercontent.com/54543428/174992436-c9a90d83-09fc-4775-ab80-6662759c1d46.png)

**Comment by dzbo** [comment]
@Hugoo @CallumGrindle this is pretty old, any plans on pushing this further?

**Comment by Hugoo** [comment]
Hey @dzbo we will take this one for the current sprint
