### ISSUE TITLE
Invalid LSP4 schema

### ISSUE THREAD

**Issue by lykhonis** [ERC725Alliance/erc725.js#200]
### I'm submitting a...

- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

### Summary

This must be address type not a uint256

https://github.com/ERC725Alliance/erc725.js/blob/develop/schemas/LSP4DigitalAsset.json#L34-L35

**Comment by Hugoo** [comment]
Indeed - nice catch ! Thanks @lykhonis - PR sent - we will release this week
