### ISSUE TITLE
Add support for `Boolean` valueContent

### ISSUE THREAD

**Issue by Hugoo** [ERC725Alliance/erc725.js#202]
https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#valueContent

Add the new valueContent in this switch:
https://github.com/ERC725Alliance/erc725.js/blob/develop/src/lib/encoder.ts#L144

Add tests

**Comment by Hugoo** [comment]
@CJ42 can you add more context for this ticket please?

Like what is the input / output for each type - as we can't see it on the specs md

**Comment by Hugoo** [comment]
Edit: `Literal` is already covered ✅

**Comment by Hugoo** [comment]
Zill be closed in. https://github.com/ERC725Alliance/erc725.js/pull/266

**Comment by CJ42** [comment]
Closing as implemented in #266
