### ISSUE TITLE
Wrong return type for `fetchData`

### ISSUE THREAD

**Issue by Hugoo** [ERC725Alliance/erc725.js#208]
When I fetch profile `await erc725.fetchData("LSP3Profile")` it expect it will return DecodeDataOutput with value field. But value  is typed as `string | string[] | URLDataWithHash` while in value  I get profile `object`

```
LSP3Profile: {
...
}
```

https://app.clickup.com/t/2mrqbvr

**Comment by CallumGrindle** [comment]
This is duplicate of #192

**Comment by Hugoo** [comment]
Ok good point - sorry ! Let's close this one then.
