### ISSUE TITLE
Add `tuple` and `CompactBytesArray` decoding

### ISSUE THREAD

**Issue by frozeman** [ERC725Alliance/erc725.js#252]
Should be able to decode `valueType` and `valueContent` of **tuples**:

`(bytes4,address,bytes4)` results in -> `["0x11223344", "0x1122334411223344112233441122334411223344", "0x11223344"]`

**CompactBytesArray:**
first byte length of bytes l, followed by bytes, follo3ed by length of next bytes.
`valueContent  = "CompactBytesArray"`
"0x**04**11223344**14**1122334411223344112233441122334411223344**04**11223344" in     
-> `["0x11223344", "0x1122334411223344112233441122334411223344", "0x11223344"]`

Should also work:
`(Bytes4,Address,Bytes4)[]`  // ABI encoded array of a tuple
`(Bytes4,Address,Bytes4)[CompactBytesArray]` // CompactBytesArray encoded tuple (cheaper)

**Comment by Hugoo** [comment]
Closed in https://github.com/ERC725Alliance/erc725.js/pull/261
