### ISSUE TITLE
Optimize for space

### ISSUE THREAD

**Issue by lykhonis** [ERC725Alliance/erc725.js#293]
### I'm submitting a...

- [ ] bug report
- [ ] feature request
- [X ] question about the decisions made in the repository
- [ ] question about how to use this project

### Summary

This library uses web3js abi encodeParameter as a way to encode raw types. I do not believe this is a good choice. There is no requirement, as far as I can tell, for encoded data to be used directly in place of EVM function invocations. This leads to a waste of space, gas, and more. e.g. boolean is encoded in form of 1 and 0 as uint256.

I suggest to change encoding and adopt flexible decoding if needed. What I mean is in few examples:
- encode(true: boolean) is 0x01
- encode(1: uint8) is 0x01
- encode(1: uint16) is 0x0001
- decode(0x01) is 1: number
- decode(0x0001) is 1: number
- encode("hello": utf8String) is 0x68656c6c6f
- decode(0x68656c6c6f) is "hello"

Few links:
- https://github.com/ERC725Alliance/erc725.js/blob/develop/src/lib/encoder.ts#L310-L385 
- https://github.com/ERC725Alliance/erc725.js/blob/develop/src/lib/encoder.test.ts#L404-L415

**Comment by CJ42** [comment]
Hi @lykhonis 

I agree about this. For single value types, the data should be encoded in the ERC725Y storage as arbitrary ("raw") bytes. There should not be any left or right padding for small types.

We have issue #277  that it is related to, where I laid out the new encoding format for these.

#288 should also fix this issue once it has been merged.
It has been taking a bit of time as we have been focused on the migration.

Maybe you can have a glance at #288 if you see any missing parts of the new re-encoding for single value types.
