### ISSUE TITLE
Weird forced gas limit on getData

### ISSUE THREAD

**Issue by karalabe** [ERC725Alliance/erc725.js#328]
https://github.com/ERC725Alliance/erc725.js/blob/9f1b5fdd0cb4eceab4396fb2d4b7fd02a8a17d2a/src/constants/constants.ts#L69

This hard codes the gas limit to 2M for retrieving a data item (or various other flavors of the ERC725Y methods). This seems arbitrary and unreasonable, especially as some contracts might want to dynamically generate data items. Unless there's some very good reason, would it be possible to remove that limitation?

**Comment by Hugoo** [comment]
Hey hi @karalabe @CJ42 ! Thanks for opening the issue!

It is indeed, this is arbitrary. It is not needed and should be changed. I believe this was set like this a while ago and we never updated it.

Similarly, the `gasPrice` is also hardcoded.

We should think about a way to make this dynamic / configurable by the user.

**Comment by CJ42** [comment]
@Hugoo This could be an option in the `ERC725` class.
