### ISSUE TITLE
[Bug] Not possible to fetch dynamic key parts individually

### ISSUE THREAD

**Issue by fhildeb** [ERC725Alliance/erc725.js#372]
### Issue

Dynamic key parts of ERC725Y storage can only be fetched when I provide more than keys:

```js
let data = await erc725js.fetchData([
  'LSP4TokenName',
  {
    keyName: 'LSP4CreatorsMap:<address>',
    dynamicKeyParts: '0x9139def55c73c12bcda9c44f12326686e3948634',
  },
]);
```

However, fetching **only one key** does not work for any dynamic objects it seems.

a) It neither works with a single key

```js
let data = await erc725js.fetchData({
  keyName: 'LSP4CreatorsMap:<address>',
  dynamicKeyParts: '0x9139def55c73c12bcda9c44f12326686e3948634',
});
```

b) Nor an array with a single key:

```js
let data = await erc725js.fetchData([{
  keyName: 'LSP4CreatorsMap:<address>',
  dynamicKeyParts: '0x9139def55c73c12bcda9c44f12326686e3948634',
}]);
```

### Why is this a problem

- No unified `fetchData` or `getData` calls, causing problems in automation
- It is not possible to retrieve data if there is **only one key**

### What I would like to know

Could someone explain 

- why this decision was made like that?
- if there is a workaround?

### Related Links 

- [Throwing in `src/lib/decodeData.ts`]( https://github.com/ERC725Alliance/erc725.js/blob/330c604f55601b634f0eea381bc542e72021d19c/src/lib/decodeData.ts#L161)
- [Related Documentation](https://github.com/ERC725Alliance/erc725.js/blob/develop/docs/classes/ERC725.md#single-key-example-1)

**Comment by richtera** [comment]
One thing I did notice is that for a single item (not array) the return is also not an array, but that should not affect a single key array input when looking at getData.
For a single key it will return the value also without array notation.
```js
  const data = await getDataMultiple(erc725Options, [keyOrKeys]);

  return data[0];
```
So I believe since fetchData uses getData instead of getDataMultiple it's not getting an array in the single item case. But it doesn't explain the single array input case.

**Comment by CJ42** [comment]
Tested with an other data key like `AddressPermissions:Permissions:<address>` works.

```js
let lsp6Result = await erc725js.getData([{ keyName: 'AddressPermissions:Permissions:<address>', dynamicKeyParts: '0x9139def55c73c12bcda9c44f12326686e3948634' }]);
```

It looks like it has to do with the fact that the valueType / valueContent is a tuple, and the error occurs here:

https://github.com/ERC725Alliance/erc725.js/blob/330c604f55601b634f0eea381bc542e72021d19c/src/lib/decodeData.ts#L272C9-L276C11

<img width="719" alt="image" src="https://github.com/ERC725Alliance/erc725.js/assets/31145285/601cb505-8813-45d9-b903-7466b5acc8f1">

**Comment by fhildeb** [comment]
@CallumGrindle could you have a look into this?
