### ISSUE TITLE
Calling `fetchData` on a profile where `JSONURL` is null should not throw an error

### ISSUE THREAD

**Issue by Hugoo** [ERC725Alliance/erc725.js#91]
### I'm submitting a...

- bug report

### Summary

![image](https://user-images.githubusercontent.com/477945/150166010-a41047ad-8854-4efc-beca-0b35525662c3.png)

It looks like when we call `.fetchData` on a profile which has a key of type JSONURL not set or set to null (while the key is in the schema provided at init) - the lib throws

This is a non working asset:

<https://universalprofile.cloud/asset/0x95be750FA80d61bC961e6DA51a64e0148bC2e34F>
-> the issue is with the issuer of this asset, not the asset itself

**Comment by CallumGrindle** [comment]
`fetchData` will log errors to console if IPFS url is undefined.

e.g. if `LSP4Metadata` key is not set on a digital asset contract outputs to console

![image](https://user-images.githubusercontent.com/54543428/151370300-c761d3d5-391b-4b3c-979d-ce4bde2846af.png)

<https://erc725-inspect.lukso.tech/inspect?address=0x2c49db8F2b077943218515f895bB3d31F4000b6f>
